export const CHANGE_URL = 'CHANGE_URL'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const CHANGE_WHITELIST = 'CHANGE_WHITELIST'
export const SWITCH_MOBILE = 'SWITCH_MOBILE'
export const SWITCH_CACHING = 'SWITCH_CACHING'
export const UPDATE_CONFIG = 'UPDATE_CONFIG'

export const TESTOVERVIEW_LOAD = 'TESTOVERVIEW_LOAD'
export const TESTOVERVIEW_SAVE = 'TESTOVERVIEW_SAVE'

export const COMPETITOR_RESULT_NEXT = 'COMPETITOR_RESULT_NEXT'
export const SPEED_KIT_RESULT_NEXT = 'SPEED_KIT_RESULT_NEXT'
export const COMPETITOR_RESULT_NEXT_SUBSCRIPTION = 'COMPETITOR_RESULT_NEXT_SUBSCRIPTION'
export const SPEED_KIT_RESULT_NEXT_SUBSCRIPTION = 'SPEED_KIT_RESULT_NEXT_SUBSCRIPTION'

export const NORMALIZE_URL_POST = 'NORMALIZE_URL_POST'
export const RATE_LIMITER_GET = 'RATE_LIMITER_GET'

export const START_TEST_COMPETITOR_POST = 'START_TEST_COMPETITOR_POST'
export const START_TEST_SPEED_KIT_POST = 'START_TEST_SPEED_KIT_POST'

export const TEST_STATUS_GET_REQUEST = 'TEST_STATUS_GET_REQUEST'
export const TEST_STATUS_GET_SUCCESS = 'TEST_STATUS_GET_SUCCESS'
export const TEST_STATUS_GET_FAILURE = 'TEST_STATUS_GET_FAILURE'

export const TERMINATE_TEST = 'TERMINATE_TEST'
