export const RESET_CONFIG = 'RESET_CONFIG'
export const CHANGE_URL = 'CHANGE_URL'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const CHANGE_TIMEOUT = 'CHANGE_TIMEOUT'
export const CHANGE_SPEED_KIT_CONFIG = 'CHANGE_SPEED_KIT_CONFIG'
export const CHANGE_COOKIE = 'CHANGE_COOKIE'
export const SWITCH_MOBILE = 'SWITCH_MOBILE'
export const SWITCH_CACHING = 'SWITCH_CACHING'
export const UPDATE_CONFIG = 'UPDATE_CONFIG'

export const TESTOVERVIEW_LOAD = 'TESTOVERVIEW_LOAD'
export const TESTOVERVIEW_NEXT = 'TESTOVERVIEW_NEXT'
export const TESTOVERVIEW_LOAD_FAIL = 'TESTOVERVIEW_LOAD_FAIL'
export const TESTOVERVIEW_SAVE = 'TESTOVERVIEW_SAVE'

export const UPDATE_TEST_PROGRESS = 'UPDATE_TEST_PROGRESS'
export const COMPETITOR_RESULT_NEXT = 'COMPETITOR_RESULT_NEXT'
export const SPEED_KIT_RESULT_NEXT = 'SPEED_KIT_RESULT_NEXT'
export const COMPETITOR_RESULT_LOAD = 'COMPETITOR_RESULT_LOAD'
export const SPEED_KIT_RESULT_LOAD = 'SPEED_KIT_RESULT_LOAD'
export const COMPETITOR_SUBSCRIPTION = 'COMPETITOR_SUBSCRIPTION'
export const SPEED_KIT_SUBSCRIPTION = 'SPEED_KIT_SUBSCRIPTION'

export const RATE_LIMITER_GET = 'RATE_LIMITER_GET'

export const INIT_TEST = 'INIT_TEST'
export const START_TEST = 'START_TEST'
export const MONITOR_TEST = 'MONITOR_TEST'
export const CONTINUE_TEST = 'CONTINUE_TEST'

export const CALL_PAGESPEED_INSIGHTS_GET = 'CALL_PAGESPEED_INSIGHTS_GET'
export const START_TEST_COMPETITOR_POST = 'START_TEST_COMPETITOR_POST'
export const START_TEST_SPEED_KIT_POST = 'START_TEST_SPEED_KIT_POST'

export const TEST_STATUS_GET = 'TEST_STATUS_GET'
export const TERMINATE_TEST = 'TERMINATE_TEST'
export const RESET_TEST_RESULT = 'RESET_TEST_RESULT'
export const RESET_TEST_STATUS = 'RESET_TEST_STATUS'

export const ADD_ERROR = "ADD_ERROR"
export const REMOVE_ERROR = "REMOVE_ERROR"
