export const CHANGE_URL = 'CHANGE_URL'
export const CHANGE_LOCATION = 'CHANGE_LOCATION'
export const SWITCH_MOBILE = 'SWITCH_MOBILE'
export const SWITCH_CACHING = 'SWITCH_CACHING'

export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'
